spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
sentry:
  dsn: https://c3aacc0cdd92295aaaab54d20da3c41e@o4506818125758464.ingest.sentry.io/4506818130280448
  # Set traces_sample_rate to 1.0 to capture 100%
  # of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647
